### ISSUE TITLE
Wrong default contrast in example

### ISSUE THREAD

**Issue by hallard** [sparkfun/GraphicLCD_Nokia_5110#7]
I spent few hours trying to get my cheap ebay Nokia LCD working, searching on sketch and wiring and even changing LCD without any success until I discovered that default contrast was too low to see anything. So changing the line 
`setContrast(40); // Good values range from 40-60`
to
`setContrast(60); // Good values range from 40-60`

Did the trick, could be great to set default value to 60, il all case good to know....

**Comment by bboyho** [comment]
Yeah, I remember that I had this issue when helping a customer out a while ago. I have a [support tip](https://learn.sparkfun.com/tutorials/graphic-lcd-hookup-guide/discuss#comment-574873fdce395f3f1c8b4569) in the comments of the hookup guide. I didn't realize that this issue was posted in the GitHub repository. I have updated the tutorial with this note. =)

---

### Contrast

If the display is not showing pixels even with the correct logic levels and [example code](https://learn.sparkfun.com/tutorials/graphic-lcd-hookup-guide#example-code-1-lcd-demo), it may just have slight variances in the way that they were manufactured. You can see the pixels faintly on the screen at an angle or pushing down on the LCD. You will need to try and set the contrast where it says `setContrast(40)` on line 87 to a value of `60`. I think there are some variances in the LCD’s contrast which might explain why certain LCDs have issues displaying defined pixels on the screen.
